### ISSUE TITLE
Create some examples for deployment

### ISSUE THREAD

**Issue by notrab** [notrab/dumbo#14]
Right now the example folder just uses the built-in php server, but we should have some examples for using other servers to run the app.

**Comment by josephajibodu** [comment]
Hello @notrab ,

I want to express my appreciation for your work on this project. It's awe-inspiring and fills a significant gap in the PHP ecosystem. I've spent considerable time searching for a solution like this, and unfortunately, many similar projects lack ongoing maintenance.

Regarding the examples, I believe you're suggesting we include configurations for various web server deployments, such as:

- Apache with mod_php
- Nginx with PHP-FPM
- Caddy

If my understanding is correct, I'd be happy to contribute to this effort.

**Comment by notrab** [comment]
Hey @josephajibodu, thanks a lot! That means a lot.

I'd love to accept a PR that adds some examples <3

It would be good if each example was its own PR, so it's easier to make clear changes if necessary before merging.

Also, if you see a way we make make the `examples` folder contain more than just an `index.php`, but instead folders, I'm happy with that!

**Comment by notrab** [comment]
@josephajibodu let me know if you want to contribute a caddy example, I'd love to learn from you on that. There's a few other examples @rayblair06 added recently with docker, which you could case your examples on.
