### ISSUE TITLE
Bearer Authentication Possibly Broken

### ISSUE THREAD

**Issue by arqbyte** [notrab/dumbo#19]
I was testing out the bearer authorization and I think it doesn't work. I am using the latest dev update.

```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Dumbo\Dumbo;
use App\Controllers\UserController;
use Dumbo\Helpers\BearerAuth;

$protectedRoutes = new Dumbo();

$token = "mysupersecret";

$protectedRoutes->use(BearerAuth::bearerAuth($token, 'Unauthorized request.'));

$protectedRoutes->get("/", function ($c) {
    return $c->json(["message" => "Welcome to the protected routes!"]);
});

$userController = new UserController();

$protectedRoutes->get('/users', function($c) use ($userController) {
    return $userController->index($c);
});

$protectedRoutes->get('/users/:id', function($c) use ($userController) {
    return $userController->show($c);
});

$protectedRoutes->post('/users', function($c) use ($userController) {
    return $userController->store($c);
});

// Route the protected routes under /api
$app->route("/api", $protectedRoutes);
```
The ``/public/index.php`` takes all the requests

```php
<?php
require_once __DIR__ . '/../vendor/autoload.php';

use Dumbo\Dumbo;

$app = new Dumbo();

/**
 * All Routes will be imported into here.
 * Each Route File will have it's work prefix endpoint
 */

require_once '../router/api.php';
require_once '../router/web.php';

$app->run();
```

Either I have made a mistake and my eyes can't spot it, or i'm just not sure.

Also I love the work!! ❤️. Many PHP Routers out there on GitHub are like 3-5 year old without any support.

**Comment by notrab** [comment]
Hey @Nyxalis, thanks for the kind words. Hopefully we can pick up some steam on this repo and keep the momentum going. I've not used PHP in over a decade, so it's been fun learning again by building this. The last time I used PHP was with CodeIgniter, and these days I want something a bit lighter than that and Laravel for my simple APIs.

regarding your issue, let me check... does it work when the protected routes are at the root level and not nested? My gut says this is an issue with the middleware in general, but I'll double check.

**Comment by notrab** [comment]
@Nyxalis I managed to fix this, and added two new examples in the process!

Thanks for letting me know. I think nested routes have never worked with middleware, so this should now make everything else work.

Thanks again 🫶

**Comment by arqbyte** [comment]
@notrab  Thanks for the response! Sorry I didn't respond earlier, I was outside.

**Comment by notrab** [comment]
@Nyxalis all good! Thanks for reporting, and let me know if you spot anything else wrong or we could add <3
