### ISSUE TITLE
Add - Get Real IP from Cloudflare

### ISSUE THREAD

**Issue by arqbyte** [notrab/dumbo#22]
I've used this to get a clients IP address to put into a database so if someone logs in with a different account I can make them verify, just like https://discord.com does. 
I am not really sure on how to make packages so I will just put the code below, incase you would like to make it a feature otherwise it can just be closed.

```php
<?php

class CloudFlare
{
    /**
     * Gets the real user IP address
     * 
     * @return string The user's IP address
     * @throws \InvalidArgumentException If no valid IP address is found
     */
    public static function getRealUserIP(): string
    {
        $ipSources = [
            'HTTP_CF_CONNECTING_IP',
            'HTTP_CLIENT_IP',
            'HTTP_X_FORWARDED_FOR',
            'REMOTE_ADDR'
        ];

        foreach ($ipSources as $source) {
            if (!empty($_SERVER[$source])) {
                $ip = $_SERVER[$source];
                if (filter_var($ip, FILTER_VALIDATE_IP)) {
                    return $ip;
                }
            }
        }

        throw new \InvalidArgumentException('No valid IP address found');
    }

    /**
     * Check if the user is using CloudFlare
     * 
     * @return bool
     */
    public static function isUsingCloudFlare(): bool
    {
        return !empty($_SERVER['HTTP_CF_CONNECTING_IP']);
    }
}
```

**Comment by notrab** [comment]
@Nyxalis I think this is useful. Does PHP work with Cloudflare Workers?

**Comment by arqbyte** [comment]
@notrab  Unfortunatley PHP cannot run on Cloudflare Workers

**Comment by notrab** [comment]
@Nyxalis ok, I'm not sure where this best fits currently since it would be nice to have features currently that are cross platform.

**Comment by arqbyte** [comment]
I am really lost @notrab, what does getting the IP address for a user and running on cloudflare works have any link?

**Comment by notrab** [comment]
@Nyxalis you said PHP doesn't run on Cloudflare, so what are you trying to achieve here exactly?

**Comment by arqbyte** [comment]
@notrab  Let's say a user creates an account onto a dashboard. There password got compromised and now anyone can login. 
The code I gave as an example let's them developer get the original users IP address, and if soemone tried logging into the dashboard with a different IP, just like discord the user will have to verify from there email that the IP is safe. Otherwise they can't login.

**Comment by notrab** [comment]
Sounds great, but I don't think this should be part of the framework, unless I'm missing something.
